### PR TITLE
Use SVG Logo instead of tinted PNG

### PR DESCRIPTION
**Pull request by JBoye**
Solves #11 / #12 by drawing the Umbraco logo directly in SVG instead of using the existing PNG logo.

I still suck at Git, so I hope i have done this correctly @leekelleher :-)

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @JBoye! The PR looks fine.

Do you know what the browser support is for SVG favicons?

The last time I checked (earlier this year) Chrome (at least on Windows) didn't support it.

**Comment by JBoye** [comment]
This method works on Chrome (Mac + Win) and Firefox, because it's drawn onto a canvas and then rasterised into PNG. 

I'm looking into Edge and Safari support now. It look like its breaking the backoffice in Edge right now..

**Comment by leekelleher** [comment]
@JBoye Ahhh cool! I didn't know that about `toDataURL`... #TIL 😉 

I'll give it a test on one of my UmbracoCloud projects. Then hopefully will merge this in.  Thanks again!

**Comment by JBoye** [comment]
Added a check for Path2D support, to avoid a blank backoffice in Edge. 

It works in Safari as well, but Safari only shows favicon when the address bar is selected

**Comment by leekelleher** [comment]
I'm not familiar with Safari myself - is that standard behaviour?

Otherwise, all sounds great! 👍

**Comment by JBoye** [comment]
Yeah, it just confused me for second :)

**Comment by leekelleher** [comment]
@JBoye Catching up after Xmas :-) Thanks again for this fix! #h5yr

**Pull request merged**
